### ISSUE TITLE
Sequence contains more than one element

### ISSUE THREAD

**Issue by Try4646** [BepInEx/Il2CppInterop#119]
Game : Zero Hour Il2cpp
MelonLoader 0.6.2

[Latest.log](https://github.com/BepInEx/Il2CppInterop/files/14609690/Latest.log)

someguy told me this on the melonloader discord server
![image](https://github.com/BepInEx/Il2CppInterop/assets/163407310/a0e7fb2d-40b2-4ea2-b9ee-e205d29b1102)

**Comment by ds5678** [comment]
```
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.FindGenericMethodGetMethod() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 163
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.Setup() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 67
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 188
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp](Delegate delegate) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/DelegateSupport.cs:line 242
   at UnityEngine.Events.UnityAction`2.op_Implicit(Action`2 )
   at MelonLoader.Support.SceneHandler.Init() in D:\a\MelonLoader\MelonLoader\Dependencies\SupportModules\SceneHandler.cs:line 26
```

`Il2CppInterop.Runtime.Injection.InjectorHelpers.FindGenericMethodGetMethod()` doesn't exist anymore.
