### ISSUE TITLE
System.InvalidOperationException: Sequence contains more than one element

### ISSUE THREAD

**Issue by Alexejhero** [BepInEx/Il2CppInterop#183]
Uno (by Ubisoft)
Unity 2022.2.21f1 (4907324dc95b)
BepInEx 6.0.0-be.725

```
[Error  :   BepInEx] System.InvalidOperationException: Sequence contains more than one element
at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
at System.Linq.Enumerable.TryGetSingle[TSource] (IEnumerable`1 source, Boolean& found)
at System.Linq.Enumerable.Single[TSource] (IEnumerable`1 source)
at Il2CppInterop.Runtime.Injection.Hooks.GenericMethod_GetMethod_Hook.FindTargetMethod() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/Hooks/GenericMethod_GetMethod_Hook.cs:line 67
at Il2CppInterop.Runtime.Injection.Hook`1.ApplyHook() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/Hook.cs:line 30
at Il2CppInterop.Runtime.Injection.InjectorHelpers.Setup() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 75
at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 196
at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp] (Delegate delegate) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/DelegateSupport.cs:line 244
at UnityEngine.Application.LogCallback.op_Implicit(Action`3 )
at BepInEx.Unity.IL2CPP.Logging.IL2CPPUnityLogSource..ctor() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Logging/IL2CPPUnityLogSource.cs:line 11
at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 88
```

Possibly related to #111 and #119

**Comment by Alexejhero** [comment]
I forgot to mention. There are two function pointers in the sequence. Trying to use either of them causes the game to hard crash. 
I spoke to 6pak about this problem, he suggested that `Object::GetVirtualMethod` might hava been inlined. I haven't had a chance ot do any testing since then but I will look into it soon.

**Comment by Alexejhero** [comment]
![image](https://github.com/user-attachments/assets/1693a10d-c34b-48de-8b6e-a29c096fb3d0)

Ubisoft drm

**Comment by ds5678** [comment]
So this can be closed?

**Comment by Alexejhero** [comment]
```cs
[HarmonyPatch]
internal static class UnwrapIl2CppCallPatch
{
    public static bool Enable { get; set; }

    [HarmonyTargetMethod, UsedImplicitly]
    private static MethodInfo TargetMethod() => AccessTools.Method("Il2CppInterop.Runtime.Injection.InjectorHelpers:GetIl2CppExport");

    [HarmonyPostfix, UsedImplicitly]
    private static void Postfix(ref nint __result)
    {
        if (!Enable) return;

        __result = XrefScannerLowLevel.JumpTargets(__result).ElementAt(1);
    }
}

[HarmonyPatch]
internal static class TargetedPatchEnabler
{
    [HarmonyTargetMethods, UsedImplicitly]
    private static IEnumerable<MethodInfo> TargetMethods() => Enumerable.Select(
    [
        "Il2CppInterop.Runtime.Injection.Hooks.Class_FromIl2CppType_Hook:FindTargetMethod",
        "Il2CppInterop.Runtime.Injection.Hooks.Class_FromName_Hook:FindTargetMethod",
        "Il2CppInterop.Runtime.Injection.Hooks.Class_GetFieldDefaultValue_Hook:FindClassGetFieldDefaultValueXref",
        "Il2CppInterop.Runtime.Injection.Hooks.GenericMethod_GetMethod_Hook:FindTargetMethod",
        "Il2CppInterop.Runtime.Injection.Hooks.MetadataCache_GetTypeInfoFromTypeDefinitionIndex_Hook:FindGetTypeInfoFromTypeDefinitionIndex",
    ], n => AccessTools.Method(n));

    [HarmonyPrefix, UsedImplicitly]
    private static void Prefix()
    {
        UnwrapIl2CppCallPatch.Enable = true;
    }

    [HarmonyPostfix, UsedImplicitly]
    private static void Postfix()
    {
        UnwrapIl2CppCallPatch.Enable = false;
    }
}
```
