### ISSUE TITLE
Error: The Long Dark 2.33

### ISSUE THREAD

**Issue by ds5678** [BepInEx/Il2CppInterop#190]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Il2CppInterop.Generator.Contexts.AssemblyRewriteContext.RewriteTypeRef(TypeSignature typeRef) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Contexts/AssemblyRewriteContext.cs:line 138
   at Il2CppInterop.Generator.Contexts.MethodRewriteContext.ProduceMethodSignatureBase() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Contexts/MethodRewriteContext.cs:line 234
   at Il2CppInterop.Generator.Contexts.MethodRewriteContext.UnmangleMethodNameWithSignature() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Contexts/MethodRewriteContext.cs:line 252
   at Il2CppInterop.Generator.Contexts.MethodRewriteContext.CtorPhase2() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Contexts/MethodRewriteContext.cs:line 108
   at Il2CppInterop.Generator.Passes.Pass18FinalizeMethodContexts.DoPass(RewriteGlobalContext context) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Passes/Pass18FinalizeMethodContexts.cs:line 27
   at Il2CppInterop.Generator.Runners.InteropAssemblyGeneratorRunner.Run(GeneratorOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Runners/InteropAssemblyGenerator.cs:line 96
   at Il2CppInterop.Generator.Il2CppInteropGenerator.Start() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Il2CppInteropGenerator.cs:line 32
   at Il2CppInterop.Generator.Il2CppInteropGenerator.Run() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Il2CppInteropGenerator.cs:line 49
```

**Comment by ds5678** [comment]
Was an upstream issue
